config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from homes.views import HomePageView, CustomRegistrationView
from homes.forms import CustomAuthenticationForm

admin.site.site_header = 'Django Property'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sales/', include('homes_for_sale.urls', namespace='sales')),
    url(r'^lettings/', include('homes_to_let.urls', namespace='lettings')),
    url(r'^user/', include('homes_user.urls', namespace='user')),
    url(r'^agents/', include('homes_agent.urls', namespace='agents')),
    url(r'^accounts/login/$', auth_views.login, {'authentication_form': CustomAuthenticationForm}, name='login'),
    url(r'^accounts/register/$', CustomRegistrationView.as_view()),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^json/', include('homes_json.urls', namespace='json')),
    url(r'^$', HomePageView.as_view(), name='homepage')
]

homes_for_sale/urls.py
from django.conf.urls import url

from .views import SearchPageView, DetailPageView, UpdateDistanceView

urlpatterns = [
    url(r'^search/$', SearchPageView.as_view(), name='search'),
    url(r'^search/details/(?P<slug>[-\w]+)/$', DetailPageView.as_view(), name='detail'),
    url(r'^search/update/$', UpdateDistanceView.as_view(), name='distance')
]

homes_json/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from .views import SearchPriceView, SearchPlacesView, ContactView, FavouriteView

urlpatterns = [
    url(r'prices/(?P<type>1|2)/$', SearchPriceView.as_view(), name='search_prices'),
    url(r'places/(?P<name>\w+)/$', SearchPlacesView.as_view(), name='search_places'),
    url(r'contact/(?P<type>sale|letting)/$', csrf_exempt(ContactView.as_view()), name='contact'),
    url(r'favourite/(?P<type>sale|letting)/(?P<slug>[-\w]+)/$', csrf_exempt(FavouriteView.as_view()), name='favourite')
]

homes/models.py
from ckeditor.fields import RichTextField

from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

from picklefield.fields import PickledObjectField
from model_utils.managers import QueryManager

from .behaviours import Publishable, Expireable, Timestampable, Orderable


class SearchPrice(models.Model):
    SEARCH_PRICE_LETTING = 1
    SEARCH_PRICE_SALE = 2
    SEARCH_PRICE_TYPES = (
        (SEARCH_PRICE_LETTING, _('Letting')),
        (SEARCH_PRICE_SALE, _('Sale'))
    )
    type = models.IntegerField(choices=SEARCH_PRICE_TYPES)
    label = models.CharField(max_length=20)
    price = models.IntegerField()

    def __str__(self):
        return self.label

    class Meta:
        pass


class PropertyType(Publishable, models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    objects = models.Manager()
    active = QueryManager(status=Publishable.STATUS_CHOICE_ACTIVE)
    inactive = QueryManager(status=Publishable.STATUS_CHOICE_INACTIVE)

    def __str__(self):
        return self.name

    class Meta:
        pass


class Branch(Publishable, Timestampable, models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    address_1 = models.CharField(max_length=100)
    address_2 = models.CharField(max_length=100, blank=True, null=True)
    address_3 = models.CharField(max_length=100, blank=True, null=True)
    town_city = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    postcode = models.CharField(max_length=10)
    location = models.PointField()
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    details = models.TextField()
    opening_hours = models.TextField()
    objects = models.Manager()
    active = QueryManager(status=Publishable.STATUS_CHOICE_ACTIVE)
    inactive = QueryManager(status=Publishable.STATUS_CHOICE_INACTIVE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = _('branch')
        verbose_name_plural = _('branches')


class Property(Publishable, Expireable, Timestampable, models.Model):
    branch = models.ForeignKey(Branch)
    property_type = models.ForeignKey(PropertyType)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    address_1 = models.CharField(max_length=100)
    address_2 = models.CharField(max_length=100, blank=True, null=True)
    address_3 = models.CharField(max_length=100, blank=True, null=True)
    town_city = models.CharField(max_length=50)
    county = models.CharField(max_length=50)
    postcode = models.CharField(max_length=10)
    location = models.PointField()
    display_address = models.CharField(max_length=200, blank=True, null=True)
    bedrooms = models.IntegerField()
    en_suites = models.IntegerField()
    receptions = models.IntegerField()
    details = RichTextField()
    summary = RichTextField(max_length=2000)
    garden = models.BooleanField(default=False)
    parking = models.BooleanField(default=False)
    retirement = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return self.title

    class Meta:
        abstract = True
        ordering = ['-updated_at']
        verbose_name = _('property')
        verbose_name_plural = _('properties')


class Feature(Timestampable, Orderable, models.Model):
    text = models.CharField(max_length=200)
    objects = models.Manager()

    def __str__(self):
        return self.text

    class Meta:
        abstract = True


class Picture(Publishable, Timestampable, Orderable, models.Model):
    caption = models.CharField(max_length=200)
    attachment = models.ImageField(upload_to='pictures/')
    objects = models.Manager()
    active = QueryManager(status=Publishable.STATUS_CHOICE_ACTIVE)
    inactive = QueryManager(status=Publishable.STATUS_CHOICE_INACTIVE)

    def __str__(self):
        return self.caption

    class Meta:
        abstract = True


class MediaType(Publishable, models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    objects = models.Manager()
    active = QueryManager(status=Publishable.STATUS_CHOICE_ACTIVE)
    inactive = QueryManager(status=Publishable.STATUS_CHOICE_INACTIVE)

    def __str__(self):
        return self.name

    class Meta:
        pass


class Media(Publishable, models.Model):
    media_type = models.ForeignKey(MediaType)
    description = models.CharField(max_length=200)
    attachment = models.FileField(upload_to='media/')
    objects = models.Manager()
    active = QueryManager(status=Publishable.STATUS_CHOICE_ACTIVE)
    inactive = QueryManager(status=Publishable.STATUS_CHOICE_INACTIVE)

    def __str__(self):
        return self.description

    class Meta:
        abstract = True


class PropertyTenure(Publishable, models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    objects = models.Manager()
    active = QueryManager(status=Publishable.STATUS_CHOICE_ACTIVE)
    inactive = QueryManager(status=Publishable.STATUS_CHOICE_INACTIVE)

    def __str__(self):
        return self.name

    class Meta:
        pass


class Contact(Timestampable, models.Model):
    more_details = models.BooleanField(default=True)
    view_property = models.BooleanField(default=True)
    title = models.CharField(max_length=10)
    forename = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    message = models.CharField(max_length=2000)
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    country = models.CharField(max_length=50)
    postcode = models.CharField(max_length=10)

    def __str__(self):
        return "%s %s (%s)" % (self.forename, self.surname, self.email)

    class Meta:
        abstract = True


class Note(Timestampable, models.Model):
    text = models.TextField()

    def __str__(self):
        return self.text

    class Meta:
        abstract = True


class Favourite(Timestampable, models.Model):
    user = models.ForeignKey(User)

    def __str__(self):
        return self.user.username

    class Meta:
        abstract = True


class Alert(Timestampable, models.Model):
    user = models.ForeignKey(User)
    key = models.CharField(max_length=40)
    criteria = PickledObjectField()

    def __str__(self):
        return self.user.username

    class Meta:
        pass


class Block(Publishable, models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    content = RichTextField()

    def __str__(self):
        return self.name

    class Meta:
        pass


class Banner(Publishable, models.Model):
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=1000)
    slug = models.SlugField(max_length=200, unique=True)
    action = models.URLField()
    label = models.CharField(max_length=50)
    attachment = models.FileField(upload_to='banners/')

    def __str__(self):
        return self.title

    class Meta:
        pass


class SEO(models.Model):
    url = models.CharField(max_length=1000, unique=True)
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=500)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.url

    class Meta:
        verbose_name = _('SEO')
        verbose_name_plural = _('SEO')

homes_for_sale/models.py
from django.utils.translation import ugettext as _
from django.urls import reverse
from django.contrib.sites.models import Site

from homes.models import *

from .querysets import SaleQuerySet


class Sale(Property):
    QUALIFIER_CHOICE_OIRO = 1
    QUALIFIER_CHOICE_OFFERS_IN_EXCESS = 2
    QUALIFIER_CHOICE_FROM = 3
    QUALIFIER_CHOICE_POA = 4
    QUALIFIER_CHOICES = (
        (QUALIFIER_CHOICE_OIRO, _('OIRO')),
        (QUALIFIER_CHOICE_OFFERS_IN_EXCESS, _('Offers in Excess of')),
        (QUALIFIER_CHOICE_FROM, _('Price from')),
        (QUALIFIER_CHOICE_POA, _('Price on Application'))
    )
    price = models.DecimalField(max_digits=11, decimal_places=2)
    qualifier = models.IntegerField(choices=QUALIFIER_CHOICES)
    new_home = models.BooleanField(default=False)
    shared_ownership = models.BooleanField(default=False)
    auction = models.BooleanField(default=False)
    property_tenure = models.ForeignKey(PropertyTenure)
    filtered = SaleQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('sales:detail', kwargs={'slug':self.slug})

    def get_full_absolute_url(self):
        site = Site.objects.get_current()
        return '{}{}'.format(str(site.domain), self.get_absolute_url())

    class Meta:
        verbose_name = _('property')
        verbose_name_plural = _('properties')


class SaleFeature(Feature):
    property = models.ForeignKey(Sale)

    class Meta:
        verbose_name = _('feature')
        verbose_name_plural = _('features')


class SalePicture(Picture):
    property = models.ForeignKey(Sale)

    class Meta:
        verbose_name = _('picture')
        verbose_name_plural = _('pictures')


class SaleMedia(Media):
    property = models.ForeignKey(Sale)

    class Meta:
        verbose_name = _('media item')
        verbose_name_plural = _('media items')


class SaleContact(Contact):
    property = models.ForeignKey(Sale)

    class Meta:
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')


class SaleNote(Note):
    property = models.ForeignKey(Sale)

    class Meta:
        verbose_name = _('note')
        verbose_name_plural = _('notes')


class SaleFavourite(Favourite):
    property = models.ForeignKey(Sale)

    class Meta:
        verbose_name = _('favourite')
        verbose_name_plural = _('favourites')

homes_for_sale/views.py
import urllib, hashlib
from urlparse import urlparse, parse_qsl

from django.utils.translation import ugettext as _
from django.views.generic import ListView, DetailView, View
from django.shortcuts import HttpResponseRedirect, reverse
from django.contrib.gis.geos import GEOSGeometry,GEOSException
from django.contrib.gis.measure import D
from django.http import Http404
from django.conf import settings

from homes.forms import SearchForm
from homes.views import BaseSearchPageView
from .models import Sale, SaleFavourite
from .forms import SaleContactForm, SaleDistanceForm
from homes.models import Alert


class SearchPageView(BaseSearchPageView, ListView):
    template_name = "homes-for-sale/search.html"
    form_class = SearchForm
    paginate_by = 9
    model = Sale

    def __get_point(self):
        try:
            return GEOSGeometry('POINT(%s %s)' % (self.request.GET.get('longitude'),self.request.GET.get('latitude')), srid=4326)
        except GEOSException as ex:
            super(SearchPageView,self).logger.error(ex)
            raise Http404(_('Location not found'))

    def __get_alert_key(self):
        return hashlib.sha1(str(self.__get_request_items())).hexdigest()

    def __get_request_items(self):
        values = {}
        for key, value in self.request.GET.items():
            values[str(key)] = str(value)
        return values

    def __is_user_subscribed(self):
        return Alert.objects.filter(user=self.request.user, key=self.__get_alert_key()).exists()

    def get_queryset(self):
        sales = Sale.filtered.published().unexpired()
        sales = sales.filter(
            price__range=(
                self.request.GET.get('min_price',10000),
                self.request.GET.get('max_price',1000000)
            )
        )
        sales = sales.filter(bedrooms__gte=self.request.GET.get('min_bedrooms',0))
        sales = sales.filter(property_type__slug=self.request.GET.get('property_type','house'))
        sales = sales.filter(location__distance_lte=(self.__get_point(),D(mi=self.request.GET.get('distance',10))))
        sales = sales.order_by('-price')
        return sales

    def get_context_data(self, **kwargs):
        context = super(SearchPageView, self).get_context_data(**kwargs)
        context['distance'] = SaleDistanceForm({'distance': self.request.GET.get('distance',10)})
        if self.request.user.is_authenticated:
            context['subscribed'] = self.__is_user_subscribed()
        else:
            context['subscribed'] = False
        return context


class DetailPageView(BaseSearchPageView, DetailView):
    template_name = "homes-for-sale/detail.html"
    form_class = SearchForm

    def __user_favorite(self):
        if self.request.user.is_authenticated:
            return SaleFavourite.objects.filter(user=self.request.user, property__slug=self.object.slug).exists()
        return False

    def get_context_data(self, **kwargs):
         context = super(DetailPageView, self).get_context_data(**kwargs)
         context['contact'] = SaleContactForm()
         context['favourited'] = self.__user_favorite()
         context['google'] = settings.GOOGLE_MAPS_API_KEY
         context['recaptcha'] = settings.RECAPTCHA_SITE_KEY
         return context

    def get_queryset(self):
        return Sale.filtered.published().unexpired()

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        obj = queryset.filter(slug=self.kwargs['slug']).first()
        if obj is None:
            raise Http404(_('Sale matching query does not exist'))
        return obj


class UpdateDistanceView(View):

    def __get_distance_params(self, form):
        url = urlparse(self.request.META.get('HTTP_REFERER'))
        params = dict(parse_qsl(url.query))
        params['distance'] = form.cleaned_data['distance']
        return params

    def post(self, request, *args, **kwargs):
        form = SaleDistanceForm(request.POST)
        if form.is_valid():
            params = self.__get_distance_params(form)
            return HttpResponseRedirect(reverse('sales:search') + '?' + urllib.urlencode(params))
        else:
            raise Http404(_('Distance not chosen'))

homes_theme_default/templates/includes/homes-for-sale/branch.html
{% load i18n %}
<div class="components--branch">
  <h2>{% trans 'Contact the Branch' %}</h2>
  <p>{{object.branch.name}}</p>
  <p class="components--branch__address"><i class="fa fa-map-pin"></i>&nbsp;{{object.branch.address_1}}, {% if object.branch.address_2 %}{{object.branch.address_2}}{% endif %}{% if object.branch.address_3 %}{{object.branch.address_3}}{% endif %}{{object.branch.town_city}}, {{object.branch.county}}</p>
  <p class="components--branch__phone"><i class="fa fa-phone"></i>&nbsp;<a href="tel:{{object.branch.telephone}}">{{object.branch.telephone}}</a></p>
  <p class="components--branch__email"><i class="fa fa-envelope"></i>&nbsp;<a href="mailto:{{object.branch.email}}">{{object.branch.email}}</a></p>
</div>

homes_theme_default/templates/includes/homes-for-sale/carousel.html
{% load thumbnail %}
{% load i18n %}
{% if object.salepicture_set.count > 0 %}
    <div id="sale-carousel" class="components--carousel carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            {% for picture in object.salepicture_set.all %}
                {% if forloop.first %}
                    <li data-target="#sale-carousel" data-slide-to="0" class="active"></li>
                {% else %}
                    <li data-target="#sale-carousel" data-slide-to="{{forloop.index}}"></li>
                {% endif %}
            {% endfor %}
        </ol>
        <div class="carousel-inner" role="listbox">
            {% for picture in object.salepicture_set.all %}
                {% if forloop.first %}
                <div class="carousel-item active">
                {% else %}
                <div class="carousel-item">
                {% endif %}
                {% thumbnail picture.attachment "750x500" crop="center" as im %}
                  <img class="d-block img-fluid" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{picture.caption}}" title="{{picture.caption}}">
                {% endthumbnail %}
                </div>
            {% endfor %}
        </div>
        <a class="carousel-control-prev" href="#sale-carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">{% trans 'Previous' %}</span>
        </a>
        <a class="carousel-control-next" href="#sale-carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">{% trans 'Next' %}</span>
        </a>
    </div>
{% endif %}

homes_theme_default/templates/includes/homes-for-sale/contact-form.html
{% load i18n %}
<div class="components--contact-form">
  <h2>{% trans 'Get In Touch' %}</h2>
  <p>{% trans 'Fill in the form below to get in touch with the agent about this property' %}</p>
  <form class="forms--contact" novalidate action="{% url 'json:contact' 'sale' %}" method="POST">
    <div class="alert" role="alert" style="display:none" tabindex="-1"></div>
    <input id="id_property" name="property" type="hidden" value="{{object.slug}}" required>
    <div class="form-group">
      <label for="{{contact.title.id_for_label}}">{% trans 'Title '%}</label>
      <select id="id_title" name="title" class="form-control">
        <option value="Mr">{% trans 'Mr' %}</option>
        <option value="Mrs">{% trans 'Mrs' %}</option>
        <option value="Miss">{% trans 'Miss' %}</option>
        <option value="Ms">{% trans 'Ms' %}</option>
        <option value="Mx">{% trans 'Mx' %}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="{{contact.forename.id_for_label}}">{% trans 'Forename' %}</label>
      {{contact.forename}}
    </div>
    <div class="form-group">
      <label for="{{contact.surname.id_for_label}}">{% trans 'Surname' %}</label>
      {{contact.surname}}
    </div>
    <div class="form-group">
      <label for="{{contact.message.id_for_label}}">{% trans 'Message' %}</label>
      {{contact.message}}
    </div>
    <div class="form-group">
      <label for="{{contact.telephone.id_for_label}}">{% trans 'Telephone' %}</label>
      {{contact.telephone}}
    </div>
    <div class="form-group">
      <label for="{{contact.email.id_for_label}}">{% trans 'Email' %}</label>
      {{contact.email}}
    </div>
    <div class="form-group">
      <label for="{{contact.country.id_for_label}}">{% trans 'Country' %}</label>
      {{contact.country}}
    </div>
    <div class="form-group">
      <label for="{{contact.postcode.id_for_label}}">{% trans 'Postcode' %}</label>
      {{contact.postcode}}
    </div>
    <div class="form-group">
      <label for="{{contact.more_details.id_for_label}}" class="custom-control custom-checkbox">
        {{contact.more_details}}
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">{% trans 'Send Property Details' %}</span>
      </label>
    </div>
    <div class="form-group">
      <label for="{{contact.view_property.id_for_label}}" class="custom-control custom-checkbox">
        {{contact.view_property}}
        <span class="custom-control-indicator"></span>
        <span class="custom-control-description">{% trans 'Arrange Property Viewing' %}</span>
      </label>
    </div>
    <button class="g-recaptcha btn btn-primary btn-block" data-sitekey="{{ recaptcha }}" data-callback="submitForm" id="id_send" name="send">
      {% trans 'Send Message' %}
    </button>
  </form>
</div>

homes_theme_default/templates/includes/homes-for-sale/features.html
{% load i18n %}
{% if object.salefeature_set.count > 0 %}
<div class="components--features">
  <h2>{% trans 'Features' %}</h2>
  <ul>
  {% for feature in object.salefeature_set.all %}
      <li>{{feature}}</li>
  {% endfor%}
  </ul>
</div>
{% endif %}

homes_theme_default/templates/includes/homes-for-sale/latest-result.html
{% load static %}
{% load thumbnail %}
{% load humanize %}
<div class="card card--latest-result">
    <div class="card--latest-result__header card-header"><i class="fa fa-map-marker"></i>&nbsp;{{ property.town_city }}, {{ property.county }}</div>
    <div class="card--latest-result__image">
        {% with property.salepicture_set.all|first as picture %}
            {% thumbnail picture.attachment "255x171" crop="center" as im %}
                <a href="{{ property.get_absolute_url }}" title="{{ property.title }}"><img class="card-img-top"  src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{picture.caption}}" title="{{picture.caption}}"></a>
            {% empty %}
                <a href="{{ property.get_absolute_url }}" title="{{ property.title }}"><img class="card-img-top"  src="{% static 'build/img/awaiting.png' %}"></a>
            {% endthumbnail %}
        {% endwith %}
    </div>
    <div class="card--latest-result__body card-body">
        <h2 class="card--latest-result__title card-title"><a href="{{ property.get_absolute_url }}">{{ property.display_address }}</a></h2>
        <h3 class="card--latest-result__price">{{property.get_qualifier_display}} &#163;{{property.price|floatformat|intcomma}}</h3>
        <p class="card--latest-result__text card-text">{{ property.summary|truncatewords:16 }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><i class="fa fa-bed"></i>&nbsp;{{ property.bedrooms }} {% if property.bedrooms > 1 %}Bedrooms{% else %}Bedroom{% endif %}</li>
        <li class="list-group-item"><i class="fa fa-bath"></i>&nbsp;{{ property.en_suites }} {% if property.en_suites > 1 %}Ensuites{% else %}Ensuite{% endif %}</li>
        <li class="list-group-item"><i class="fa fa-handshake-o"></i>&nbsp;{{ property.receptions }} {% if property.receptions > 1 %}Reception Rooms {% else %}Reception Room{% endif %}</li>

    </ul>
    <div class="card-footer">
        <a href="{{ property.get_absolute_url }}" class="btn btn-block btn-primary">More Details</a>
    </div>
</div>

homes_theme_default/templates/includes/homes-for-sale/search-button.html
{% load i18n %}
{% if request.GET %}
<div class="components--search-button">
  <p><a href="{% url 'sales:search' %}?{{ request.GET.urlencode }}" class="btn btn-primary btn-block">{% trans 'Back To Search' %}</a></p>
</div>
{% endif %}

homes_theme_default/templates/includes/homes-for-sale/search-result.html
{% load thumbnail %}
{% load humanize %}
{% load static %}
<div class="card card--search-result{% if last %} card--search-result__last{% endif %}">
    <div class="card-header"><i class="fa fa-map-marker"></i>&nbsp;{{ property.town_city }}, {{ property.county }}<span class="card--search-result__price">{{property.get_qualifier_display}} &#163;{{property.price|floatformat|intcomma}}</span></div>
    <div class="card-body">
        <div class="row">
            <div class="col-xs-12 col-sm-4 col-md-3">
                {% with property.salepicture_set.all|first as picture %}
                    {% thumbnail picture.attachment "285x200" crop="center" as im %}
                        <a href="{{ property.get_absolute_url }}?{{ request.GET.urlencode }}"><img class="d-block img-fluid" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{picture.caption}}" title="{{picture.caption}}"></a>
                    {% empty %}
                        <a href="{{ property.get_absolute_url }}?{{ request.GET.urlencode }}"><img class="d-block img-fluid" src="{% static 'build/img/awaiting.png' %}"></a>
                    {% endthumbnail %}
                {% endwith %}
            </div>
            <div class="col-xs-12 col-sm-8 col-md-9">
                <h2 class="card--search-result__title"><a href="{{ property.get_absolute_url }}?{{ request.GET.urlencode }}">{{property.title}}</a></h2>
                <h3 class="card--search-result__display-address">{{ property.display_address }}</h3>
                <p>{{property.summary}}</p>
                <ul class="card--search-result__list">
                    <li><i class="fa fa-bed"></i>&nbsp;{{ property.bedrooms }} {% if property.bedrooms > 1 %}Bedrooms{% else %}Bedroom{% endif %}</li>
                    <li><i class="fa fa-bath"></i>&nbsp;{{ property.en_suites }} {% if property.en_suites > 1 %}Ensuites{% else %}Ensuite{% endif %}</li>
                    <li><i class="fa fa-handshake-o"></i>&nbsp;{{ property.receptions }} {% if property.receptions > 1 %}Reception Rooms {% else %}Reception Room{% endif %}</li>
                </ul>
            </div>
        </div>
    </div>
</div>