config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from homes.views import HomePageView, CustomRegistrationView
from homes.forms import CustomAuthenticationForm

admin.site.site_header = 'Django Property'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sales/', include('homes_for_sale.urls', namespace='sales')),
    url(r'^lettings/', include('homes_to_let.urls', namespace='lettings')),
    url(r'^user/', include('homes_user.urls', namespace='user')),
    url(r'^agents/', include('homes_agent.urls', namespace='agents')),
    url(r'^accounts/login/$', auth_views.login, {'authentication_form': CustomAuthenticationForm}, name='login'),
    url(r'^accounts/register/$', CustomRegistrationView.as_view()),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^json/', include('homes_json.urls', namespace='json')),
    url(r'^$', HomePageView.as_view(), name='homepage')
]

homes_to_let/urls.py
from django.conf.urls import url

from .views import SearchPageView, DetailPageView, UpdateDistanceView

urlpatterns = [
    url(r'^search/$', SearchPageView.as_view(), name='search'),
    url(r'^search/details/(?P<slug>[-\w]+)/$', DetailPageView.as_view(), name='detail'),
    url(r'^search/update/$', UpdateDistanceView.as_view(), name='distance')
]

homes_user/urls.py
from django.conf.urls import url

from .views import UserDashboardPageView, UserFavouriteView, UserSubscribeView

urlpatterns = [
    url(r'^dashboard/$', UserDashboardPageView.as_view(), name='dashboard'),
    url(r'^favourite/(?P<type>sale|letting)/(?P<slug>[-\w]+)/$', UserFavouriteView.as_view(), name='favourite'),
    url(r'^subscribe/$', UserSubscribeView.as_view(), name='subscribe'),
]

homes_to_let/models.py
from django.utils.translation import ugettext as _
from django.urls import reverse
from django.contrib.sites.models import Site

from homes.models import *
from .querysets import LettingQuerySet


class Letting(Property):
    RENTAL_PERIOD_WEEKLY = 1
    RENTAL_PERIOD_MONTHLY = 2
    RENTAL_PERIOD_ANNUALLY = 3
    RENTAL_PERIOD_CHOICES = (
        (RENTAL_PERIOD_WEEKLY, _('Weekly')),
        (RENTAL_PERIOD_MONTHLY, _('Monthly')),
        (RENTAL_PERIOD_ANNUALLY, _('Annually'))
    )
    TYPE_OF_LET_LONG_TERM = 1
    TYPE_OF_LET_SHORT_TERM = 2
    TYPE_OF_LET_STUDENT = 3
    TYPE_OF_LET_CHOICES = (
        (TYPE_OF_LET_LONG_TERM, _('Long Term')),
        (TYPE_OF_LET_SHORT_TERM, _('Short Term')),
        (TYPE_OF_LET_STUDENT, _('Student'))
    )
    rental = models.DecimalField(max_digits=11, decimal_places=2)
    period = models.IntegerField(choices=RENTAL_PERIOD_CHOICES)
    type_of_let = models.IntegerField(choices=TYPE_OF_LET_CHOICES)
    furnished = models.BooleanField(default=False)
    house_share = models.BooleanField(default=False)
    let_agreed = models.BooleanField(default=False)
    available_at = models.DateTimeField()
    filtered = LettingQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('lettings:detail', kwargs={'slug':self.slug})

    def get_full_absolute_url(self):
        site = Site.objects.get_current()
        return '{}{}'.format(str(site.domain), self.get_absolute_url())

    class Meta:
        verbose_name = _('property')
        verbose_name_plural = _('properties')


class LettingFeature(Feature):
    property = models.ForeignKey(Letting)

    class Meta:
        verbose_name = _('feature')
        verbose_name_plural = _('features')


class LettingPicture(Picture):
    property = models.ForeignKey(Letting)

    class Meta:
        verbose_name = _('picture')
        verbose_name_plural = _('pictures')


class LettingMedia(Media):
    property = models.ForeignKey(Letting)

    class Meta:
        verbose_name = _('media item')
        verbose_name_plural = _('media items')


class LettingContact(Contact):
    property = models.ForeignKey(Letting)

    class Meta:
        verbose_name = _('contact')
        verbose_name_plural = _('contacts')


class LettingNote(Note):
    property = models.ForeignKey(Letting)

    class Meta:
        verbose_name = _('note')
        verbose_name_plural = _('notes')


class LettingFavourite(Favourite):
    property = models.ForeignKey(Letting)

    class Meta:
        verbose_name = "favourite"
        verbose_name_plural = _('favourites')

homes_to_let/forms.py
from django.utils.translation import ugettext as _
from django.forms import ModelForm, Textarea, TextInput, EmailInput, CheckboxInput
from django import forms

from .models import LettingContact


class LettingContactForm(ModelForm):
    class Meta:
        model = LettingContact
        fields = [
            'more_details','view_property','title','forename','surname',
            'message','telephone','email','country','postcode'
        ]
        widgets = {
            'forename': TextInput(attrs={'class':'form-control'}),
            'surname': TextInput(attrs={'class':'form-control'}),
            'message': Textarea(attrs={'cols':10,'rows':5,'class':'form-control'}),
            'telephone': TextInput(attrs={'class':'form-control'}),
            'email': EmailInput(attrs={'class':'form-control'}),
            'country': TextInput(attrs={'class':'form-control'}),
            'postcode': TextInput(attrs={'class':'form-control'}),
            'more_details': CheckboxInput(attrs={'class':'custom-control-input'}),
            'view_property': CheckboxInput(attrs={'class':'custom-control-input'})
        }
        error_messages = {
            'forename':{
                'required': _('Forename is required'),
            },
            'surname':{
                'required': _('Surname is required'),
            },
            'message':{
                'required': _('Message is required'),
            },
            'telephone':{
                'required': _('Telephone is required'),
            },
            'email':{
                'required': _('Email address is required'),
            },
            'country':{
                'required': _('Country is required'),
            },
            'postcode':{
                'required': _('Postcode is required'),
            },
        }


class LettingDistanceForm(forms.Form):
    distance = forms.ChoiceField(choices=[(10,_('10 Miles')),(20,_('20 Miles'))])

homes_to_let/views.py
import urllib, hashlib
from urlparse import urlparse, parse_qsl

from django.utils.translation import ugettext as _
from django.views.generic import ListView, DetailView, View
from django.shortcuts import HttpResponseRedirect, reverse, Http404
from django.contrib.gis.geos import GEOSGeometry, GEOSException
from django.contrib.gis.measure import D
from django.conf import settings

from homes.forms import SearchForm
from homes.views import BaseSearchPageView
from .models import Letting, LettingFavourite
from .forms import LettingContactForm, LettingDistanceForm
from homes.models import Alert


class SearchPageView(BaseSearchPageView, ListView):
    template_name = "homes-to-let/search.html"
    form_class = SearchForm
    paginate_by = 9
    model = Letting

    def __get_point(self):
        try:
            return GEOSGeometry('POINT(%s %s)' % (self.request.GET.get('longitude'),self.request.GET.get('latitude')), srid=4326)
        except GEOSException as ex:
            super(SearchPageView,self).logger.error(ex)
            raise Http404('Location not found')

    def __get_alert_key(self):
        return hashlib.sha1(str(self.__get_request_items())).hexdigest()

    def __get_request_items(self):
        values = {}
        for key, value in self.request.GET.items():
            values[str(key)] = str(value)
        return values

    def __is_user_subscribed(self):
        return Alert.objects.filter(user=self.request.user, key=self.__get_alert_key()).exists()

    def get_queryset(self):
        lettings = Letting.filtered.published().unexpired()
        lettings = lettings.filter(
            rental__range=(
                self.request.GET.get('min_price',10000),
                self.request.GET.get('max_price',1000000)
            )
        )
        lettings = lettings.filter(bedrooms__gte=self.request.GET.get('min_bedrooms',0))
        lettings = lettings.filter(property_type__slug=self.request.GET.get('property_type','house'))
        lettings = lettings.filter(location__distance_lte=(self.__get_point(),D(mi=self.request.GET.get('distance',10))))
        lettings = lettings.order_by('-rental')        
        return lettings

    def get_context_data(self, **kwargs):
        context = super(SearchPageView, self).get_context_data(**kwargs)
        context['distance'] = LettingDistanceForm({'distance': self.request.GET.get('distance',10)})
        if self.request.user.is_authenticated:
            context['subscribed'] = self.__is_user_subscribed()
        else:
            context['subscribed'] = False
        return context


class DetailPageView(BaseSearchPageView, DetailView):
    template_name = "homes-to-let/detail.html"
    form_class = SearchForm

    def __is_user_favourite(self):
        if self.request.user.is_authenticated and self.object:
            return LettingFavourite.objects.filter(user=self.request.user, property__slug=self.object.slug).exists()
        return False

    def get_context_data(self, **kwargs):
        context = super(DetailPageView, self).get_context_data(**kwargs)
        context['contact'] = LettingContactForm()
        context['favourited'] = self.__is_user_favourite()
        context['google'] = settings.GOOGLE_MAPS_API_KEY
        context['recaptcha'] = settings.RECAPTCHA_SITE_KEY
        return context

    def get_queryset(self):
        return Letting.filtered.published().unexpired()

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        obj = queryset.filter(slug=self.kwargs['slug']).first()
        if obj is None:
            raise Http404(_('Letting matching query does not exist'))
        return obj

class UpdateDistanceView(View):
    def __get_distance_params(self, form):
        url = urlparse(self.request.META.get('HTTP_REFERER'))
        params = dict(parse_qsl(url.query))
        params['distance'] = form.cleaned_data['distance']
        return params

    def post(self, request, *args, **kwargs):
        form = LettingDistanceForm(request.POST)
        if form.is_valid():
            params = self.__get_distance_params(form)
            return HttpResponseRedirect(reverse('lettings:search') + '?' + urllib.urlencode(params))
        else:
            raise Http404(_('Distance not chosen'))

homes_theme_default/templates/homes-to-let/detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block stylesheets %}
  {{block.super}}
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.min.css">
{% endblock %}
{% block content %}
    {% include 'includes/forms/search.html' %}
    <section class="section--property-detail">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-8">
                    <article class="article--property">
                      <header class="article--property__header">
                        <h2 class="article--property__title">{{object.title}}<span class="article--property__actions"><a href="{% url 'json:favourite' 'letting' object.slug %}" title="{% if favourited %}{% trans 'Click to unfavourite this property' %}{% else %}{% trans 'Click to favourite this property' %}{%endif%}" class="toggle--link" data-active="fa-heart" data-inactive="fa-heart-o">{% if favourited %}<i class="fa fa-heart"></i>{% else %}<i class="fa fa-heart-o"></i>{% endif %}</a></span></h2>
                        <h3 class="article--property__display-address">{{object.display_address}}<span class="article--property__price">&#163;{{object.rental}} {{object.get_period_display}}</span></h3>
                      </header>
                      {% include "includes/homes-to-let/carousel.html" %}
                      <div class="article--property__details">
                        <ul class="nav nav-tabs" id="details" role="tablist">
                          <li class="nav-item">
                            <a class="nav-link active" id="description-tab" data-toggle="tab" href="#descriptiontab" role="tab" aria-controls="description" aria-expanded="true">{% trans 'Description' %}</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" id="map-tab" data-toggle="tab" href="#maptab" role="tab" aria-controls="profile">{% trans 'Map &amp; Streetview' %}</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" id="downloads-tab" data-toggle="tab" href="#downloadstab" role="tab" aria-controls="profile">{% trans 'Brochures &amp; Floorplans' %}</a>
                          </li>
                        </ul>
                        <div class="tab-content" id="detailsContent">
                          <div class="tab-pane fade show active" id="descriptiontab" role="tabpanel" aria-labelledby="description-tab">
                            {{object.details|linebreaks}}
                          </div>
                          <div class="tab-pane fade" id="maptab" role="tabpanel" aria-labelledby="map-tab">
                            <div id="map" class="components--gmap"></div>
                          </div>
                          <div class="tab-pane fade" id="downloadstab" role="tabpanel" aria-labelledby="downloads-tab">
                            {% if object.salemedia_set.count > 0 %}
                              <ul>
                              {% for media in object.salemedia_set.all %}
                                <li>{{media.media_type}} - <a href="{{media.attachment.url}}" target="_blank">{{media}}</a></li>
                              {% endfor %}
                              </ul>
                            {% else %}
                              <p>{% trans 'Sorry, there are no downloads for this property' %}</p>
                            {% endif %}
                          </div>
                        </div>
                      </div>
                    </article>
                </div>
                <div class="col-sm-12 col-md-4">
                  {% include "includes/homes-to-let/search-button.html" %}
                  {% include "includes/homes-to-let/branch.html" %}
                  {% include "includes/homes-to-let/features.html" %}
                  {% include "includes/homes-to-let/contact-form.html" %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block footer_scripts %}
    {{block.super}}
    <script src="{% static 'build/js/details.bundle.js' %}"></script>
    <script src="{% static 'build/js/form.bundle.js' %}"></script>
    <script>
    var map;
    function initMap(){
      var location = {lat:{{object.location.y}}, lng:{{object.location.x}}};
      map = new google.maps.Map(document.getElementById('map'), {
        center: location,
        zoom: 12
      });
      var marker = new google.maps.Marker({
        position: location,
        map: map,
        title: "{{object.display_address}}"
      });
    }
    function submitForm(token){
        var form = document.querySelector('.forms--contact');
        window.form.default.handleFormSubmit(form, token);
    }
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      if ($(e.target).attr('id')){
        initMap();
      }
    });
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key={{google}}" async defer></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

homes_theme_default/templates/homes-to-let/search.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load filter_tags %}
{% block content %}
    {% include 'includes/forms/search.html' %}
    <section class="section--search-extra">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-2">
                    <label style="margin-top:0.35rem">{% trans 'Distance' %}</label>
                </div>
                <div class="col-xs-12 col-sm-7">
                    <form action="{% url 'lettings:distance' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-xs-12 col-sm-6">
                                {{ distance.distance|add_css:'form-control' }}
                            </div>
                            <div class="col-xs-12 col-sm-6">
                                <input type="submit" class="btn btn-primary btn-block" value="{% trans 'Update' %}">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-xs-12 col-sm-3">
                    {% if subscribed %}
                        <a href="{% url 'user:subscribe' %}?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="btn btn-warning btn-block">{% trans 'Unsubscribe from Email Alerts' %}</a>
                    {% else %}
                        <a href="{% url 'user:subscribe' %}?{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="btn btn-success btn-block">{% trans 'Subscribe to Email Alerts' %}</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
    <section class="section--search-results">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h2 class="section--search-results__title">{% trans 'Homes To Let Results' %}</h2>
                    {% include 'includes/alerts/messages.html' %}
                    {% for property in object_list %}
                        {% include "includes/homes-to-let/search-result.html" with last=forloop.last %}
                    {% empty %}
                        <p>{% trans 'No properties were found for your search' %}</p>
                    {% endfor %}
                    {% include 'includes/pagination.html' %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block footer_scripts %}
    {{ block.super }}
    <script src="{% static 'build/js/search.bundle.js' %}"></script>
{% endblock %}