config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from homes.views import HomePageView, CustomRegistrationView
from homes.forms import CustomAuthenticationForm

admin.site.site_header = 'Django Property'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sales/', include('homes_for_sale.urls', namespace='sales')),
    url(r'^lettings/', include('homes_to_let.urls', namespace='lettings')),
    url(r'^user/', include('homes_user.urls', namespace='user')),
    url(r'^agents/', include('homes_agent.urls', namespace='agents')),
    url(r'^accounts/login/$', auth_views.login, {'authentication_form': CustomAuthenticationForm}, name='login'),
    url(r'^accounts/register/$', CustomRegistrationView.as_view()),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^json/', include('homes_json.urls', namespace='json')),
    url(r'^$', HomePageView.as_view(), name='homepage')
]

homes_to_let/urls.py
from django.conf.urls import url

from .views import SearchPageView, DetailPageView, UpdateDistanceView

urlpatterns = [
    url(r'^search/$', SearchPageView.as_view(), name='search'),
    url(r'^search/details/(?P<slug>[-\w]+)/$', DetailPageView.as_view(), name='detail'),
    url(r'^search/update/$', UpdateDistanceView.as_view(), name='distance')
]

homes_user/urls.py
from django.conf.urls import url

from .views import UserDashboardPageView, UserFavouriteView, UserSubscribeView

urlpatterns = [
    url(r'^dashboard/$', UserDashboardPageView.as_view(), name='dashboard'),
    url(r'^favourite/(?P<type>sale|letting)/(?P<slug>[-\w]+)/$', UserFavouriteView.as_view(), name='favourite'),
    url(r'^subscribe/$', UserSubscribeView.as_view(), name='subscribe'),
]

homes_user/views.py
import hashlib

from braces.views import LoginRequiredMixin, GroupRequiredMixin

from django.utils.translation import ugettext as _
from django.views.generic import TemplateView, View
from django.shortcuts import get_object_or_404, reverse, HttpResponseRedirect
from django.contrib import messages

from homes_for_sale.models import SaleFavourite, Sale
from homes_to_let.models import LettingFavourite, Letting
from homes.models import Alert


class UserFavouriteView(LoginRequiredMixin, GroupRequiredMixin, View):
    group_required = "general"

    def __get_sale_favourite(self, slug):
        sale = get_object_or_404(Sale, slug=slug)
        return SaleFavourite.objects.filter(property=sale, user=self.request.user).first()

    def __get_letting_favourite(self, slug):
        letting = get_object_or_404(Letting, slug=slug)
        return LettingFavourite.objects.filter(property=letting, user=self.request.user).first()

    def get(self, request, *args, **kwargs):
        if kwargs['type'] == 'sale':
            favourite = self.__get_sale_favourite(kwargs['slug'])
        else:
            favourite = self.__get_letting_favourite(kwargs['slug'])
        if favourite:
            favourite.delete()
            messages.add_message(request, messages.WARNING, _('You have deleted the selected favourite'))
        return HttpResponseRedirect(reverse('user:dashboard'))


class UserDashboardPageView(LoginRequiredMixin, GroupRequiredMixin, TemplateView):
    template_name = "homes-user/dashboard.html"
    group_required = "general"

    def get_context_data(self, **kwargs):
        context = super(UserDashboardPageView, self).get_context_data(**kwargs)
        context['favourites'] = {
            'sale': SaleFavourite.objects.filter(user=self.request.user),
            'letting': LettingFavourite.objects.filter(user=self.request.user)
        }
        context['alerts'] = Alert.objects.filter(user=self.request.user)
        return context


class UserSubscribeView(LoginRequiredMixin, GroupRequiredMixin, View):
    group_required = "general"

    def __get_alert_key(self):
        return hashlib.sha1(str(self.__get_request_items())).hexdigest()

    def __get_request_items(self):
        values = {}
        for key, value in self.request.GET.items():
            values[str(key)] = str(value)
        return values

    def __get_or_create_alert(self, key):
        return Alert.objects.get_or_create(
            user=self.request.user,
            key=key,
            defaults={'criteria': self.__get_request_items()}
        )

    def get(self, request, *args, **kwargs):
        obj, created = self.__get_or_create_alert(self.__get_alert_key())
        if created:
            messages.add_message(request, messages.SUCCESS, _('You have subscribed to an email alert for this search'))
        else:
            obj.delete()
            messages.add_message(request, messages.WARNING, _('You were unsubscribed from an email alert for this search'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

homes_theme_default/templates/homes-user/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load filter_tags %}
{% load inclusion_tags %}
{% block stylesheets %}
  {{block.super}}
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block content %}
  {% page_header 'Dashboard' %}
  <section class="section--user-dashboard">
      <div class="container">
          <div class="row">
              <div class="col-12">
                {% include 'includes/alerts/messages.html' %}
                <h3>{% trans 'Favourited Properties' %}</h3>
                <p>{% trans 'Shown below are the properties you have favourited on the website' %}</p>
                <h4>{%trans 'Sales' %}</h4>
                {% if favourites.sale %}
                  <p>{% trans 'Property for sale favourites' %}</p>
                  <ul class="components--user-favourites">
                  {% for favourite in favourites.sale %}
                    <li><a href="{% url 'user:favourite' 'sale' favourite.property.slug %}" class="btn btn-primary btn-sm"><i class="fa fa-trash"></i></a>&nbsp;<a href="{% url 'sales:detail' favourite.property.slug %}">{{favourite.property}}</a></li>
                  {% endfor %}
                  </ul>
                {% else %}
                  <p>{% trans 'No property for sale favourites' %}</p>
                {% endif %}
                <h4>{% trans 'Lettings' %}</h4>
                {% if favourites.letting %}
                  <p>{% trans 'Property to let favourites' %}</p>
                  <ul class="components--user-favourites">
                    {% for favourite in favourites.letting %}
                      <li><a href="{% url 'lettings:detail' favourite.property.slug %}">{{favourite.property}}</a><span><a href="{% url 'user:favourite' 'letting' favourite.property.slug %}"><i class="fa fa-trash"></i></a></span></li>
                    {% endfor %}
                  </ul>
                {% else %}
                  <p>{% trans 'No property to let favourites' %}</p>
                {% endif %}
                <h3>{% trans 'Property Alerts' %}</h3>
                {% if alerts %}
                  <p>{% trans 'Shown below are the alerts you have subscribed to on the website' %}</p>
                  <ul class="components--user-alerts">
                  {% for alert in alerts %}
                      <li><a href="{{alert.criteria|link_criteria}}" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>&nbsp;<a href="{{alert.criteria|delete_link_criteria}}" class="btn btn-primary btn-sm"><i class="fa fa-trash"></i></a>&nbsp;{{alert.criteria|format_criteria}}</li>
                  {% endfor %}
                  </ul>
                {% else %}
                  <p>{% trans 'No alerts added for your account' %}</p>
                {% endif %}
              </div>
          </div>
      </div>
  </section>
{% endblock %}